[package]
name = "hinata"
version = "0.1.2"
edition = "2024"

[dependencies]
thiserror = "2.0.18"
num-derive = "0.4.2"
num-traits = "0.2.19"
byteorder = "1.5.0"
async-trait = "0.1.89"
hidapi = "2.6.4"
tokio = { version = "1.49.0", features = ["full"] }
